{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "targetgroup-senpai.fullname" . }}-clusterrole
  labels:
    {{- include "targetgroup-senpai.labels" . | nindent 4 }}
rules:
# Read permissions for services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Read permissions for nodes
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Read permissions for pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
{{- end }}