{{- if .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "targetgroup-senpai.fullname" . }}-secret
  labels:
    {{- include "targetgroup-senpai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}